// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// =========================================================================
// TRUSTSHARE FILE REGISTRY SMART CONTRACT (Enhanced Version)
// =========================================================================
// Features:
// 1. File ownership and immutable metadata
// 2. Access request / approval with public-key exchange
// 3. Encrypted key reference sharing (via Encryption Module)
// 4. Digital signature verification support
// 5. Detailed events for backend/frontend integration
// =========================================================================

contract FileRegistry {
    
    // =====================================================================
    // DATA STRUCTURES
    // =====================================================================
    
    struct FileRecord {
        address owner;              // Ethereum address of the file owner
        string meta;                // JSON metadata (file info, timestamps, etc.)
        string encryptedKeyRef;     // Reference to encrypted decryption key (IPFS hash or DB key)
        string digitalSignature;    // Digital signature from the uploader (for verification)
        bool exists;                // Whether the file is registered
    }

    struct AccessRequest {
        address requester;          // Address of user requesting access
        string publicKey;           // Requester's public key for encryption
        bool approved;              // Whether the request has been approved
        bool exists;                // Whether the request exists
    }

    // =====================================================================
    // EVENTS
    // =====================================================================
    event FileUploaded(bytes32 indexed hash, address indexed owner, string meta);
    event FileUploadedWithSignature(bytes32 indexed hash, address indexed owner, string signature);
    event AccessRequested(bytes32 indexed fileHash, address indexed requester);
    event AccessApproved(bytes32 indexed fileHash, address indexed requester, string encryptedKeyRef);

    event AccessRequestedDetailed(
        bytes32 indexed fileHash,
        address indexed requester,
        string fileId,
        string message
    );

    event AccessApprovedDetailed(
        bytes32 indexed fileHash,
        address indexed requester,
        string encryptedKeyRef,
        string fileId,
        string message
    );

    // =====================================================================
    // STATE VARIABLES
    // =====================================================================
    mapping(bytes32 => FileRecord) public files;
    mapping(bytes32 => mapping(address => AccessRequest)) public requests;
    mapping(bytes32 => mapping(address => string)) private encryptedKeys;

    // =====================================================================
    // CORE FUNCTIONS
    // =====================================================================

    /**
    * @dev Upload and register a new file on the blockchain with signature
    * @param hash Unique file identifier (generated by backend)
    * @param meta File metadata (JSON string)
    * @param signature Digital signature of the file for authenticity verification
    */
    function upload(bytes32 hash, string calldata meta, string calldata signature) external {
        require(!files[hash].exists, "File already registered");
        
        // Create new file record
        files[hash] = FileRecord({
            owner: msg.sender,
            meta: meta,
            encryptedKeyRef: "",
            digitalSignature: signature,
            exists: true
        });

        // Emit standard event
        emit FileUploaded(hash, msg.sender, meta);

        // Optional: Emit signature separately (for Etherscan logging)
        emit FileUploadedWithSignature(hash, msg.sender, signature);
    }

    

    /**
     * @dev Request access to an existing file (providing public key)
     * @param fileHash File hash
     * @param requesterPublicKey Requester's public key
     */
    function requestAccess(
    bytes32 fileHash,
    string calldata requesterPublicKey,
    string calldata meta
    ) external {
        require(files[fileHash].exists, "File not found");
        require(!requests[fileHash][msg.sender].exists, "Request already exists");
        require(bytes(requesterPublicKey).length > 0, "Public key required");

        requests[fileHash][msg.sender] = AccessRequest({
            requester: msg.sender,
            publicKey: requesterPublicKey,
            approved: false,
            exists: true
        });

        emit AccessRequested(fileHash, msg.sender);
        emit AccessRequestedDetailed(fileHash, msg.sender, "", meta); // "" for fileId, meta for message
}

    /**
     * @dev Approve access request and share encrypted decryption key
     * @param fileHash File hash
     * @param requester Address of user being approved
     * @param encryptedKeyRef Encrypted file key (from EncryptionModule)
     */
    function approveAccess(
        bytes32 fileHash,
        address requester,
        string calldata encryptedKeyRef,
        string calldata meta
    ) external {
        require(files[fileHash].exists, "File not found");
        require(files[fileHash].owner == msg.sender, "Only owner can approve");
        require(requests[fileHash][requester].exists, "Request not found");
        require(bytes(encryptedKeyRef).length > 0, "Invalid encrypted key");

        requests[fileHash][requester].approved = true;
        encryptedKeys[fileHash][requester] = encryptedKeyRef;

        files[fileHash].encryptedKeyRef = encryptedKeyRef;

        emit AccessApproved(fileHash, requester, encryptedKeyRef);
        emit AccessApprovedDetailed(fileHash, requester, encryptedKeyRef, "", meta); // "" for fileId, meta for message
    }

   
    // =====================================================================
    // VIEW FUNCTIONS
    // =====================================================================

    function getEncryptedKey(bytes32 fileHash, address requester) external view returns (string memory) {
        require(files[fileHash].exists, "File not found");
        return encryptedKeys[fileHash][requester];
    }

    function getRequesterPublicKey(bytes32 fileHash, address requester) external view returns (string memory) {
        require(files[fileHash].exists, "File not found");
        require(requests[fileHash][requester].exists, "Access request not found");
        return requests[fileHash][requester].publicKey;
    }

    /**
     * @dev Get file information (owner, metadata, encrypted key, signature, exists)
     */
    function getFileInfo(bytes32 fileHash) external view returns (
        address owner,
        string memory meta,
        string memory encryptedKeyRef,
        string memory digitalSignature,
        bool exists
    ) {
        require(files[fileHash].exists, "File not found");
        FileRecord memory record = files[fileHash];
        return (
            record.owner,
            record.meta,
            record.encryptedKeyRef,
            record.digitalSignature,
            record.exists
        );
    }

    /**
     * @dev Check if a user has access to the file
     */
    function hasAccess(bytes32 fileHash, address user) external view returns (bool) {
        if (!files[fileHash].exists) return false;
        if (files[fileHash].owner == user) return true;
        return requests[fileHash][user].approved;
    }
}
